theme: jekyll-theme-minimal
logo: /assets/logo.png
android_link: https://play.google.com/store/apps/details?id=com.driveturnout.Turnout
ios_link: https://tools.applemediaservices.com/app/1535843967
email: hello@driveturnout.com